services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pickledex-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RICK_AND_MORTY_API_URL=${RICK_AND_MORTY_API_URL}
    restart: always
